### ISSUE TITLE
Book 2, version 2022-08-08, section 6.11

### ISSUE THREAD

**Issue by behrman** [probml/pml2-book#128]
page 300, line 30: $X \subset Y$ -> $X \subsetneq Y$
page 300, line 38: each others' -> each other's
page 302, lines 28-29: You define $m$ in two places, circularly. Below is a possible fix. You could also rewrite to make clear the distinction between the vector and the set function.
page 302, line 28: where $m : 2^V \rightarrow \mathbb{R}$ -> where $m \in \mathbb{R}^V$
page 302, line 29: we have that $m(A)$ -> we define $m(A)$
page 303, line 21: $m_{u,a}$ -> $m_u(a)$
page 304, line 17: $m_u(v) = 1$ -> $m_u(v) = 0$
page 305, lines 31-34: If you wish to be consistent earlier notation: $m_{u,a}$ -> $m_u(a)$
page 309, lines 31-32: $V$ -> $|V|$
page 309, line 38: are also based continuous -> are also based on continuous
page 309, lines 39-42: Is the $n$ here the same as $|V|$ above? If so, it would be good to use $|V|$ throughout.
page 311, line 40: corset -> coreset
page 311, line 41: how do we construct submodular function -> how do we construct a submodular function
page 312, line 40: cases we wish -> cases, we wish
page 313, line 13: Alternatively, one also “learn” a submodular function -> Alternatively, one can also “learn” a submodular function
page 314, line 32: Wording can be improved: This can be seen quickly􏰗 easily
page 314, line 42: second order partial derivative -> second-order partial derivative
page 314, line 45: have this property but in fact -> have this property, but in fact
page 315, line 9: I think you meant: There are an almost limited number -> There are an almost unlimited number
page 315, line 45: where $U_t$ is the set of labeled samples -> where $U_t$ is the set of unlabeled samples
page 317, line 7: restrictions as well and this has been widely used -> restrictions as well, and this has been widely used
page 317, line 16: $x$ consists of a homogeneous and for this reason -> ??

**Comment by bilmes** [comment]
Hi @behrman  these are great, thanks! They are all fixed in a recent checkin, and are also fixed in the long arxiv version of the paper (https://arxiv.org/abs/2202.00132 ) and this will be reflected the next time it is pushed to arxiv (note that some of the typos below were fixed before, including in the 10/16/2022 version of the book). But thanks, please keep them coming!

> page 300, line 30: 
 - fixed

>page 300, line 38: 
 - fixed in earlier typo fixes (e.g., 10/16/ version).

>page 302, lines 28-29:

  - now using different font for the set element milk and the name of a modular function.

>page 302, line 28:
>page 302, line 29: we have that  -> we define 

  - re-wrote this set so that we don't need yet another letter for the elements of the vector part of a modular function.

>page 303, line 21: 

  - fixed
 
>page 304, line 17:  

  - fixed 

>page 305, lines 31-34: 

  - fixed everywhere (I hope)

>page 309, lines 31-32: 

   - fixed

>page 309, line 38: are also based continuous -> are also based on continuous

   - fixed

>page 309, lines 39-42: Is the  here the same as  above? If so, it would be good to use  throughout.

   - agreed, fixed.

>page 311, line 40: corset -> coreset

    - fixed
    
>page 311, line 41: how do we construct submodular function -> how do we construct a submodular function

   - was fixed in 10/16 version.

>page 312, line 40: cases we wish -> cases, we wish

   - was fixed in 10/16 version

>page 313, line 13: Alternatively, one also “learn” a submodular function -> Alternatively, one can also “learn” a submodular function

    - fixed
>page 314, line 32: Wording can be improved: This can be seen quickly􏰗 easily

    - fixed

>page 314, line 42: second order partial derivative -> second-order partial derivative

    - fixed
    
>page 314, line 45: have this property but in fact -> have this property, but in fact

   - fixed
  
>page 315, line 9: I think you meant: There are an almost limited number -> There are an almost unlimited number

   - fixed :-)

>page 315, line 45: where  is the set of labeled samples -> where  is the set of unlabeled samples

    - fixed

>page 317, line 7: restrictions as well and this has been widely used -> restrictions as well, and this has been widely used

    - fixed 
    - 
>page 317, line 16:  consists of a homogeneous and for this reason -> ??

   - fixed (also fixed an earlier, it should be p(x) \propto exp(-E(x)) for energy function E(x).
