### ISSUE TITLE
Typo in Equations 3.54-3.56 Version: 2022-04-01 ?

### ISSUE THREAD

**Issue by hovnatan** [probml/pml2-book#260]
In equations 3.54-3.56, should l(theta|x), s(theta|x), s'(theta|x) be instead l(x|theta), s(x|theta), s'(x|theta)?

**Comment by maremita** [comment]
Hi,
I think the notation is correct. They are _likelihood_-related functions of unknown parameters $\theta$ given fixed data $x$.
$l(\theta|x)$ is the log-likelihood and is given by the log of the PMF of the binomial distribution $p(x|\theta)$ (where the scaling factor $\binom{n}{x}$ is dropped because is independent of $\theta$ (section 3.2.1.1)).

**Comment by murphyk** [comment]
Exactly. What @maremita  said.
